_wandb:
    value:
        cli_version: 0.25.1
        e:
            v64jvcnqn96se7bw2k9o7sruijnglifz:
                args:
                    - --mode
                    - sweep
                codePath: prova-wandb.py
                codePathLocal: prova-wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "497958244352"
                        used: "326921916416"
                email: pietrofazion04@gmail.com
                executable: /home/pietro/anaconda3/envs/grid-ai/bin/python3
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-99eacb1d-2c2b-d4a4-e7fa-d1e9b50b4579
                host: cachyos
                memory:
                    total: "16627204096"
                os: Linux-6.19.10-1-cachyos-x86_64-with-glibc2.43
                program: /home/pietro/Documenti/doorkey/prova-wandb.py
                python: CPython 3.10.19
                root: /home/pietro/Documenti/doorkey
                startedAt: "2026-04-10T10:25:22.841019Z"
                writerId: v64jvcnqn96se7bw2k9o7sruijnglifz
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 14
                - 16
                - 61
            "4": 3.10.19
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
alpha:
    value: 0.14169002368961023
env_id:
    value: MiniGrid-DoorKey-6x6-v0
eps_decay:
    value: 0.9999
eps_end:
    value: 0.1
eps_start:
    value: 1
gamma:
    value: 0.999
n_episodes:
    value: 5000
