_wandb:
    value:
        cli_version: 0.25.1
        e:
            vxkbchg8q4aa5263wdq3t2ah39eey2zi:
                args:
                    - --mode
                    - sweep
                codePath: prova6-8x8.py
                codePathLocal: prova6-8x8.py
                email: pietrofazion04@gmail.com
                executable: /home/pietro/anaconda3/envs/grid-ai/bin/python3
                host: cachyos
                os: Linux-6.19.10-1-cachyos-x86_64-with-glibc2.43
                program: /home/pietro/Documenti/doorkey/prova6-8x8.py
                python: CPython 3.10.19
                root: /home/pietro/Documenti/doorkey
                startedAt: "2026-04-11T21:00:39.342612Z"
                writerId: vxkbchg8q4aa5263wdq3t2ah39eey2zi
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 14
                - 16
            "4": 3.10.19
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
alpha:
    value: 0.01
drop_rate:
    value: 0.3
env_id:
    value: MiniGrid-DoorKey-8x8-v0
eps_end:
    value: 0.05
eps_start:
    value: 1
gamma:
    value: 0.95
n_episodes:
    value: 12000
n_steps:
    value: 8
shaping_scale:
    value: 0.5
